### PR TITLE
Add patch to process quickqusars mocks v9.0.*

### PR DESCRIPTION
**Pull request by alxogm**
This PR is intended to fixe an error that occurs for the latest version of the mocks, that arise when coadding them, See [this issue](https://github.com/paulmartini/baltools/issues/3).

 However, a new issue appeared due to a recent change in desispec. The error that arise is: 

```
ERROR:coaddition.py:231:coadd_cameras: Cannot directly coadd the camera spectra because wavelength are not aligned, use --lin-step or --log10-step to resample to a common grid
{'brz': array([3569.30004883, 3570.10004883, 3570.90004883, ..., 9831.70004883,
       9832.50004883, 9833.30004883])}
resampled flux
Traceback (most recent call last):
  File "/global/homes/a/alxogm/desi/code/others/baltools/py/baltools/desibal.py", line 91, in desibalfinder
    specobj = coadd_cameras(specobj, cosmics_nsig=None)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/coaddition.py", line 232, in coadd_cameras
    sys.exit(12)
SystemExit: 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/a/alxogm/desi/code/others/baltools/bin/runbalfinder_pixel.py", line 46, in <module>
    db.desibalfinder(specfilename, overwrite=args.redo, verbose=False)
  File "/global/homes/a/alxogm/desi/code/others/baltools/py/baltools/desibal.py", line 98, in desibalfinder
    specobj = coadd_cameras(specobj, cosmics_nsig=None)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/coaddition.py", line 355, in coadd_cameras
    fibermap = coadd_fibermap(spectra.fibermap)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/coaddition.py", line 75, in coadd_fibermap
    tfmap['COADD_EXPTIME'][i] = np.sum(fibermap['EXPTIME'][jj][good_coadds])
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'EXPTIME'
```

And I think is due to [this recent change]( https://github.com/desihub/desispec/commit/94cd4e5ebf8b275a68915794f1c017574689ff46#diff-66db6b690c4424fead9a749ff0b362d172abddd338ecb6ca34c965b4a0858e32.  )

### CODE REVIEW

**Review by paulmartini — APPROVED** [review]
Thank you for this PR, @alxogm. Looks like the PR is labeled as still in progress. Let me know when it is ready to merge.

**Comment by alxogm** [comment]
Hi @paulmartini please don't merge yet. Let me try to solve the other issue, I marked the PR as draft as it is not ready for merge. Thanks.

**Comment by alxogm** [comment]
@paulmartini issue above is fixed but   I'm getting this error now (was not getting it before, because I hadn0t updated my repository),

Traceback (most recent call last):
  File "/global/homes/a/alxogm/desi/code/others/baltools/bin/runbalfinder_pixel.py", line 46, in <module>
    db.desibalfinder(specfilename, overwrite=args.redo, verbose=False)
  File "/global/homes/a/alxogm/desi/code/others/baltools/py/baltools/desibal.py", line 128, in desibalfinder
    baltable.initbaltab_desi(fm[qsos], zs[zqsos], balfilename, overwrite=overwrite)
  File "/global/homes/a/alxogm/desi/code/others/baltools/py/baltools/baltable.py", line 117, in initbaltab_desi
    col5 = fits.Column(name='MJD', format='E', array=specdata['MJD'])
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'MJD'

 but I don't see DESI spectra have the 'MJD' column? so we don't have it in the mocks either... maybe is in a header or somewhere else?

**Comment by alxogm** [comment]
@paulmartini I see, it is there for the data in the fibermap, but not for the mock... let me trace why... sorry.

**Comment by alxogm** [comment]
@paulmartini I understood the source of the latest error, and since there are various mocks that will not have this column, I though of leaving it empty. Given the recent discussion about disk space occupied by the mocks, I'll be revising the fibermap content for the mocks so, I'll include to decide if we'll have an MJD column, but even if we include it we still need to be able to run in existing mocks, so If you agree with the proposed changes, then I think is good to merge. 

I tested with the following lines: 

```
mockdir=/global/project/projectdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0_Y1/v9.0.3/desiY1-0.3/spectra-16/0/0/
runbalfinder_pixel.py -i $mockdir/spectra-16-0.fits
```

**Comment by paulmartini** [comment]
Thank you for this PR, @alxogm! Looks good to me, and I have merged.

**Pull request merged**
